# Generated by Django 3.2.4 on 2021-10-17 20:58

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=100)),
                ('id_image', models.ImageField(blank=True, help_text='Picture of the id ', upload_to='ids')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('product_category_image', models.ImageField(blank=True, upload_to='upload_productcategory_image')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vendor', models.CharField(max_length=50)),
                ('name_of_shop', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('phone_number1', models.CharField(blank=True, max_length=15)),
                ('biz_registration', models.ImageField(blank=True, upload_to='upload_vendor_details_image')),
                ('shop_place_image', models.ImageField(blank=True, upload_to='upload_vendor_details_image')),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('id_image', models.ImageField(upload_to='upload_vendor_details_image')),
                ('current_image', models.ImageField(blank=True, help_text='current image please', upload_to='upload_vendor_details_image')),
                ('email_add', models.EmailField(max_length=250, unique=True)),
                ('location', django_google_maps.fields.AddressField(max_length=200)),
                ('ghana_post_address', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='newcom.ProductCategory')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcom.ids')),
            ],
        ),
    ]
